import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from tkinter.scrolledtext import ScrolledText
import subprocess
import threading
import os
import re
import sys

# Regex to remove ANSI escape codes (colors) generated by Rich
ANSI_ESCAPE = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

class TriAgentGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("🧠 Tri-Agent Swarm | Multimodal Benchmarks")
        self.root.geometry("850x650")
        self.root.configure(bg="#1E1E2E")  # Dark theme

        style = ttk.Style()
        style.theme_use('clam')
        style.configure('TFrame', background='#1E1E2E')
        style.configure('TLabel', background='#1E1E2E', foreground='#CDD6F4', font=('Segoe UI', 11))
        style.configure('TButton', background='#89B4FA', foreground='#11111B', font=('Segoe UI', 10, 'bold'), borderwidth=0, padding=6)
        style.map('TButton', background=[('active', '#B4BEFE')])
        style.configure('TRadiobutton', background='#1E1E2E', foreground='#CDD6F4', font=('Segoe UI', 10))
        style.map('TRadiobutton', background=[('active', '#1E1E2E')])
        style.configure('TCombobox', font=('Segoe UI', 11))

        self.selected_paths = []
        self.is_running = False

        self._build_ui()

    def _build_ui(self):
        main_frame = ttk.Frame(self.root, padding="20")
        main_frame.pack(fill=tk.BOTH, expand=True)

        # Header
        header = tk.Label(main_frame, text="Tri-Agent Multimodal Pipeline", bg="#1E1E2E", fg="#89B4FA", font=('Segoe UI', 20, 'bold'))
        header.pack(pady=(0, 20))

        # Config Frame
        config_frame = ttk.Frame(main_frame)
        config_frame.pack(fill=tk.X, pady=10)

        # 1. Selection Mode
        ttk.Label(config_frame, text="1. Select Input Type:").grid(row=0, column=0, sticky="w", pady=5)
        self.selection_mode = tk.StringVar(value="folder")
        radio_frame = ttk.Frame(config_frame)
        radio_frame.grid(row=0, column=1, sticky="w", padx=10)
        ttk.Radiobutton(radio_frame, text="Entire Folder", variable=self.selection_mode, value="folder").pack(side=tk.LEFT, padx=(0, 10))
        ttk.Radiobutton(radio_frame, text="Specific Files", variable=self.selection_mode, value="files").pack(side=tk.LEFT)

        # Browse Button
        self.btn_browse = ttk.Button(config_frame, text="Browse Media...", command=self.browse_media)
        self.btn_browse.grid(row=0, column=2, padx=10)

        self.lbl_selected = ttk.Label(config_frame, text="No media selected", foreground="#A6ADC8", font=('Segoe UI', 9, 'italic'))
        self.lbl_selected.grid(row=1, column=0, columnspan=3, sticky="w", pady=(0, 15))

        # 2. Language Selection
        ttk.Label(config_frame, text="2. Base Language:").grid(row=2, column=0, sticky="w", pady=5)
        self.language_var = tk.StringVar(value="Tamil")
        self.lang_dropdown = ttk.Combobox(config_frame, textvariable=self.language_var, values=["Tamil", "Hindi", "Telugu"], state="readonly", width=15)
        self.lang_dropdown.grid(row=2, column=1, sticky="w", padx=10)

        # Run Button
        self.btn_run = tk.Button(main_frame, text="▶ START GENERATION", bg="#A6E3A1", fg="#11111B", font=('Segoe UI', 12, 'bold'), 
                                 borderwidth=0, padx=20, pady=10, cursor="hand2", command=self.start_generation)
        self.btn_run.pack(pady=20)

        # Output Console
        ttk.Label(main_frame, text="Live Output:").pack(anchor="w")
        
        self.console = ScrolledText(main_frame, bg="#11111B", fg="#A6ADC8", font=('Consolas', 10), wrap=tk.WORD)
        self.console.pack(fill=tk.BOTH, expand=True, pady=(5, 0))
        self.console.config(state=tk.DISABLED)

    def browse_media(self):
        mode = self.selection_mode.get()
        if mode == "folder":
            folder = filedialog.askdirectory(title="Select Dataset Folder")
            if folder:
                self.selected_paths = [folder]
                self.lbl_selected.config(text=f"Selected Folder: {folder}")
        else:
            files = filedialog.askopenfilenames(
                title="Select Media Files", 
                filetypes=[
                    ("All Media", "*.png *.jpg *.jpeg *.webp *.mp4 *.avi *.mov *.mp3 *.wav *.m4a"), 
                    ("All Files", "*.*")
                ]
            )
            if files:
                self.selected_paths = list(files)
                self.lbl_selected.config(text=f"Selected {len(files)} file(s)")

    def log(self, message):
        self.console.config(state=tk.NORMAL)
        self.console.insert(tk.END, message + "\n")
        self.console.see(tk.END)
        self.console.config(state=tk.DISABLED)

    def start_generation(self):
        if not self.selected_paths:
            messagebox.showwarning("Missing Input", "Please select a folder or files first.")
            return

        if self.is_running:
            return

        self.is_running = True
        self.btn_run.config(state=tk.DISABLED, text="⏳ RUNNING...", bg="#F9E2AF")
        self.btn_browse.config(state=tk.DISABLED)
        
        # Clear console
        self.console.config(state=tk.NORMAL)
        self.console.delete(1.0, tk.END)
        self.console.config(state=tk.DISABLED)

        # Run in a background thread so the GUI doesn't freeze
        thread = threading.Thread(target=self._run_pipeline, daemon=True)
        thread.start()

    def _run_pipeline(self):
        language = self.language_var.get()
        output_dir = f"./output/{language.lower()}"
        mode = self.selection_mode.get()

        self.log(f"Initializing Tri-Agent Pipeline for {language}...")
        self.log(f"Output will automatically save to: {output_dir}\n")

        env = os.environ.copy()
        env["PYTHONUTF8"] = "1"  # Fix windows encoding for Rich borders

        # Build the command based on user selection
        if mode == "folder":
            cmd = [sys.executable, "-m", "triagent", "batch", "--media-dir", self.selected_paths[0], "-l", language, "-o", output_dir]
        else:
            # For multiple files, we'll just loop and use 'run' command
            pass

        try:
            if mode == "folder":
                self._execute_cmd(cmd, env)
            else:
                for file_path in self.selected_paths:
                    cmd = [sys.executable, "-m", "triagent", "run", "--media", file_path, "-l", language, "-o", output_dir]
                    self.log(f"\n--- Processing File: {os.path.basename(file_path)} ---")
                    self._execute_cmd(cmd, env)
                    
            self.log("\n✅ ALL GENERATIONS COMPLETE!")
        except Exception as e:
            self.log(f"\n❌ ERROR: {str(e)}")
        finally:
            self.root.after(0, self._reset_ui)

    def _execute_cmd(self, cmd, env):
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding='utf-8', env=env)
        
        # Read output line by line in real-time
        for line in process.stdout:
            clean_line = ANSI_ESCAPE.sub('', line).rstrip('\n')
            # Use root.after to safely update GUI from background thread
            self.root.after(0, self.log, clean_line)

        process.wait()
        if process.returncode != 0:
            self.root.after(0, self.log, f"\nProcess exited with code {process.returncode}")

    def _reset_ui(self):
        self.is_running = False
        self.btn_run.config(state=tk.NORMAL, text="▶ START GENERATION", bg="#A6E3A1")
        self.btn_browse.config(state=tk.NORMAL)


if __name__ == "__main__":
    root = tk.Tk()
    app = TriAgentGUI(root)
    root.mainloop()
