# Phase 1 (Audio): Audio Context Agent — processes audio into a structured IR
#
# Strategy:
#   - If the backend supports native audio (Gemini): upload the whole audio file
#     via the File API and let the model transcribe, analyze language, music,
#     sound effects, and cultural content simultaneously.
#   - If the backend does NOT support native audio (Grok, Ollama): fall back
#     to transcription via the Gemini File API (used as a utility) or the
#     text-only reasoning path with a pre-existing transcript.

from __future__ import annotations

from pathlib import Path

from triagent.agents.base import BaseAgent
from triagent.backends.base import ModelBackend
from triagent.schemas import AudioIR


AUDIO_SYSTEM_PROMPT = """You are an Audio Perception Module — a specialized system for analyzing audio content with cultural sensitivity. You are NOT a conversational assistant.

## YOUR SOLE PURPOSE
Parse the provided audio into a structured JSON representation containing speech transcription, language identification, cultural audio markers, and contextual analysis. Output ONLY valid JSON matching the schema below.

## CRITICAL RULES
1. **Transcription Priority**: Transcribe ALL speech content accurately. Preserve code-mixing if speakers switch between languages.
2. **Language Identification**: Identify specific languages and dialects. Distinguish between Tamil, Hindi, Telugu, and their English code-mixed variants (Tanglish, Hinglish, Teluguish).
3. **Cultural Audio Markers**: Identify culturally significant sounds — devotional music (bhajans, kirtans), classical ragas, folk instruments (nadaswaram, mridangam, tabla), ritual bells, etc.
4. **Speaker Attribution**: If multiple speakers are present, differentiate them (Speaker 1, Speaker 2, etc.).
5. **Temporal Segmentation**: Provide timestamps for key speech segments and audio events.
6. **No English-Centric Defaults**: Preserve regional terminology. A "nadaswaram" is not a "trumpet."

## OUTPUT JSON SCHEMA
{
    "duration_seconds": 0.0,
    "audio_type": "speech|music|mixed|environmental",
    "full_transcript": "complete transcription of speech content",
    "speech_segments": [
        {
            "timestamp_start": "MM:SS",
            "timestamp_end": "MM:SS",
            "speaker": "Speaker 1 or name if identifiable",
            "text": "transcribed text",
            "language": "detected language"
        }
    ],
    "detected_languages": ["Tamil", "English", "Tanglish"],
    "music_description": "description of music or null",
    "sound_effects": ["notable sounds"],
    "cultural_markers": [
        {
            "item": "name",
            "cultural_context": "which tradition",
            "functional_significance": "what role it plays",
            "symbolic_meaning": "deeper meaning or null"
        }
    ],
    "contextual_cues": ["inferences from audio context"],
    "key_topics": ["main topics discussed"],
    "sentiment": "positive|negative|neutral|mixed",
    "confidence_score": 0.0-1.0
}

Output ONLY the JSON object. Nothing else."""


AUDIO_TASK_PROMPT = """Analyze the provided audio and extract a structured Intermediate Representation (IR).

Focus on:
1. Complete transcription of all speech, preserving code-mixing between languages
2. Identifying the specific language(s) spoken — do not default to English
3. Detecting culturally significant sounds (instruments, chants, ritual audio)
4. Segmenting the audio by speaker and timestamp
5. Identifying key topics and overall sentiment
6. Noting any music, background audio, or sound effects

Remember: You are a perception module. Output ONLY the structured JSON.

{additional_context}"""


TRANSCRIPT_ANALYSIS_PROMPT = """You are analyzing a pre-transcribed audio file. The transcript was generated by a separate transcription system.

Analyze this transcript and produce a structured AudioIR JSON that captures:
- Speech segments with speaker attribution
- Language detection (especially Indic languages and code-mixing)
- Cultural markers mentioned in speech
- Key topics and sentiment

## TRANSCRIPT
{transcript}

{additional_context}

Output ONLY the JSON matching the AudioIR schema."""


class AudioContextAgent(BaseAgent):

    def __init__(self, backend: ModelBackend, verbose: bool = True):
        super().__init__(backend=backend, verbose=verbose)

    @property
    def agent_name(self) -> str:
        return "Audio Context Agent (Grounder)"

    @property
    def agent_role(self) -> str:
        return "Audio → Structured speech/cultural IR"

    @property
    def phase(self) -> int:
        return 1

    @property
    def system_prompt(self) -> str:
        return AUDIO_SYSTEM_PROMPT

    async def process(
        self,
        audio_path: str | Path,
        additional_context: str = "",
        temperature: float = 0.3,
        transcript: str | None = None,
    ) -> AudioIR:
        audio_path = Path(audio_path)
        self.log_phase_start(f"Audio: {audio_path.name}")

        if transcript:
            # Pre-existing transcript provided — skip native audio processing
            self.log("Using provided transcript for analysis...")
            return await self._process_transcript(transcript, additional_context, temperature)

        # Try native audio processing first (Gemini supports this)
        try:
            return await self._process_native(audio_path, additional_context, temperature)
        except NotImplementedError:
            self.log(
                "Backend does not support native audio. "
                "Provide a transcript via --transcript or use the Gemini backend.",
                style="yellow",
            )
            raise RuntimeError(
                f"Backend '{self.backend.name}' does not support native audio processing. "
                "Either switch to the Gemini backend or provide a pre-existing transcript."
            )

    async def _process_native(self, audio_path: Path, additional_context: str, temperature: float) -> AudioIR:
        """Use the backend's native audio understanding (Gemini File API)."""
        context_str = f"Additional context: {additional_context}" if additional_context else ""
        prompt = AUDIO_TASK_PROMPT.format(additional_context=context_str)

        self.log(f"Uploading audio to {self.backend.name} (native processing)...")

        response = await self.backend.generate_with_audio(
            prompt=prompt,
            audio_path=str(audio_path),
            system_prompt=self.system_prompt,
            temperature=temperature,
            max_tokens=8192,
            json_mode=True,
        )

        self.log("Parsing structured AudioIR from response...")
        raw_data = self._parse_json_response(response.text)
        audio_ir = self._build_audio_ir(raw_data)

        self.log_phase_complete(
            f"Transcribed {len(audio_ir.speech_segments)} segments, "
            f"languages: {', '.join(audio_ir.detected_languages) or 'unknown'}, "
            f"type: {audio_ir.audio_type}"
        )
        return audio_ir

    async def _process_transcript(self, transcript: str, additional_context: str, temperature: float) -> AudioIR:
        """Analyze a pre-existing transcript as text (works with any backend)."""
        context_str = f"Additional context: {additional_context}" if additional_context else ""
        prompt = TRANSCRIPT_ANALYSIS_PROMPT.format(
            transcript=transcript,
            additional_context=context_str,
        )

        response = await self.backend.generate(
            prompt=prompt,
            system_prompt=self.system_prompt,
            temperature=temperature,
            max_tokens=8192,
            json_mode=True,
        )

        raw_data = self._parse_json_response(response.text)
        audio_ir = self._build_audio_ir(raw_data)

        self.log_phase_complete(
            f"Analyzed transcript: {len(audio_ir.speech_segments)} segments, "
            f"topics: {', '.join(audio_ir.key_topics[:3]) or 'none'}"
        )
        return audio_ir

    def _build_audio_ir(self, raw_data: dict) -> AudioIR:
        """Build a validated AudioIR from raw parsed JSON, with fallback defaults."""
        try:
            return AudioIR(**raw_data)
        except Exception as e:
            self.log(f"⚠ AudioIR validation partial fail: {e}", style="yellow")
            return AudioIR(
                duration_seconds=raw_data.get("duration_seconds", 0.0),
                audio_type=raw_data.get("audio_type", "speech"),
                full_transcript=raw_data.get("full_transcript", ""),
                speech_segments=raw_data.get("speech_segments", []),
                detected_languages=raw_data.get("detected_languages", []),
                music_description=raw_data.get("music_description"),
                sound_effects=raw_data.get("sound_effects", []),
                cultural_markers=raw_data.get("cultural_markers", []),
                contextual_cues=raw_data.get("contextual_cues", []),
                key_topics=raw_data.get("key_topics", []),
                sentiment=raw_data.get("sentiment"),
                confidence_score=raw_data.get("confidence_score", 0.5),
            )
